name: maprefresh

on:
  workflow_dispatch:
  schedule:
    - cron: "0,30 * * * *"

permissions:
  contents: write
  pages: write
  id-token: write


jobs:
  sftp-download:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: Install Duck CLI
        run: |
          echo -e "deb https://s3.amazonaws.com/repo.deb.cyberduck.io stable main" | sudo tee /etc/apt/sources.list.d/cyberduck.list > /dev/null
          sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys FE7097963FEFBE72
          sudo apt-get update
          sudo apt-get install -y duck

      - name: Download from SFTP with Duck
        env:
          SFTP_HOST: ${{ secrets.SFTP_HOST }}
          SFTP_USER: ${{ secrets.SFTP_USER }}
          SFTP_PASS: ${{ secrets.SFTP_PASS }}
        run: |
          duck --username $SFTP_USER --password $SFTP_PASS -y --parallel 8 --download $SFTP_HOST server-download

      - name: Upload to GitHub Pages
        uses: actions/upload-pages-artifact@v4
        with:
          path: server_download/

      - name: Deploy GitHub Pages
        uses: actions/deploy-pages@v4
      
          
