name: maprefresh

on:
  workflow_dispatch:
  schedule:
    - cron: "0,30 * * * *"

permissions:
  contents: write
  pages: write
  id-token: write


jobs:
  sftp-download:
    runs-on: ubuntu-latest
    environment:
      name: github-pages

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: Install Duck CLI
        run: |
          echo -e "deb https://s3.amazonaws.com/repo.deb.cyberduck.io stable main" | sudo tee /etc/apt/sources.list.d/cyberduck.list > /dev/null
          sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys FE7097963FEFBE72
          sudo apt-get update
          sudo apt-get install -y duck

      - name: Download from SFTP with Duck
        env:
          SFTP_HOST: ${{ secrets.SFTP_HOST }}
          SFTP_USER: ${{ secrets.SFTP_USER }}
          SFTP_PASS: ${{ secrets.SFTP_PASS }}
        run: |
          mkdir -p server_download
          duck --username $SFTP_USER --password $SFTP_PASS -y --parallel 8 --download $SFTP_HOST server-download

      - name: Commit downloaded files
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Update files from SFTP server" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Build Jekyll for GitHub Pages
        uses: actions/jekyll-build-pages@v1.0.13

      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v4.0.0

      - name: Deploy GitHub Pages site
        uses: actions/deploy-pages@v4.0.5

      
          
